spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslMode=VERIFY_IDENTITY&serverTimezone=Asia/Seoul&enabledTLSProtocols=TLSv1.2,TLSv1.3
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      data-source-properties:
        rewriteBatchedStatements: true
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc.batch_size: 20
        default_batch_fetch_size: ${chunkSize:100}

logging:
  level:
    com.gemmap.gemmap: INFO
    org.springframework.security: WARN

# OCI Object Storage 설정 (S3 호환)
s3:
  base-path: dev/spots/

# Dev 환경 설정
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  max-age: 3600