apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spot-service.fullname" . }}
  labels: {{- include "spot-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "spot-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "spot-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8082
