apiVersion: v1
kind: Service
metadata:
  name: {{ include "spot-service.fullname" . }}
  labels: {{- include "spot-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "spot-service.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8082
