apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service
    service: user
  name: user-service
  namespace: dev
spec:
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: user-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-service
    service: user
  name: user-service
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        service: user
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: user-service-secret
        image: docker.io/gemmap/user-service:dev-latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/liveness
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        name: app
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 800m
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 512Mi
