apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../../base/spot-service
  - networkpolicy.yaml
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: spot-service
