spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${SPOT_DB_HOST}:${SPOT_DB_PORT}/${SPOT_DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: ${SPOT_DB_USERNAME}
    password: ${SPOT_DB_PASSWORD}
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      data-source-properties:
        rewriteBatchedStatements: true
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc.batch_size: 20
        default_batch_fetch_size: ${chunkSize:100}

logging:
  level:
    com.gemmap.spot: DEBUG
    com.gemmap.common: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

# Local 환경 JWT 설정 (user-service와 동일하게 설정)
jwt:
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}     # 1시간
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:86400000}  # 1일

# NHN Cloud Object Storage 설정
s3:
  base-path: local/spots/
