apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gemmap-api
  namespace: dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - example.com   # 환경별 오버레이에서 실제 호스트로 패치
      secretName: gemmap-tls
  rules:
    - host: example.com # 환경별 오버레이에서 패치
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gemmap-service
                port:
                  number: 8080